backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "index"
    label: "Index"
    files:
      - file: "src/pages/index/index.md"
        label: "Index"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Hero, name: hero, widget: object, fields:
              [
                {label: "Hero Title", name: "title", widget: "string"},
                {label: "Hero Description", name: "description", widget: "markdown"}
              ]
            }
          - {label: About, name: about, widget: object, fields:
              [
                {label: "About Title", name: "title", widget: "string"},
                {label: "About Description Col 1", name: "col_1", widget: object, fields:
                  [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Description", name: "description", widget: "markdown"}
                  ]
                },
                {label: "About Description Col 2", name: "col_2", widget: object, fields:
                  [
                    {label: "Title", name: "title", widget: "string"},
                    {label: "Description", name: "description", widget: "markdown"}
                  ]
                }
              ]
            }
          - {label: Location, name: loc, widget: object, fields:
              [
                {label: "Location Title", name: "title", widget: "string"},
                {label: "Location Description", name: "description", widget: "markdown"},
                {label: "Location Marker", name: "marker", widget: "markdown"},
                {label: "Location Coords", name: "coords", widget: object, fields:
                  [
                    {label: "Latitude", name: "lat", widget: "number"},
                    {label: "Longitude", name: "lng", widget: "number"}
                  ]
                }
              ]
          }
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}